config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :microposts
  resources :relationships ,only: [:create, :destroy]
  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}

  
  mount_uploader :picture, AvatarUploader
  
  validates :picture,
            :file_size => {
                :maximum => 1.megabytes.to_i
            }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email = self.email.downcase}
  validates :name, presence: true,length:{maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length:{maximum: 255},format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :location, absence: true, 
                       on: :create
  validates :location, allow_blank: true, 
                       length: { minimum: 2, maximum: 20 }, 
                       on: :update
  has_secure_password
  has_many :microposts
  
  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  #uploader 
  mount_uploader :avatar, AvatarUploader
  
  
 #他のユーザのフォロー
 def follow(other_user)
   following_relationships.find_or_create_by(followed_id: other_user.id)
 end
 
 #フォローしているユーザをアンフォロー
 def unfollow(other_user)
   following_relationship = following_relationships.find_by(followed_id: other_user.id)
   following_relationship.destroy if following_relationship
 end
 
 #あるユーザをフォローいているか？
 def following?(other_user)
   following_users.include?(other_user)
 end
 
 #つぶやき取得
 def feed_items
   Micropost.where(user_id: following_user_ids + [self.id])
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  
   private
   def logged_in_user
    unless logged_in?
     store_location
     flash[:danger] ="Please Logged in."
     redirect_to login_url
    end
   end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    
    before_action :logged_in_user, only: [:create]
    
    
    
    def create
       @micropost = current_user.microposts.build(micropost_params) 
       if @micropost.save
           flash[:success]="Micropost created!"
           redirect_to root_url
       else
           @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page])
           render 'static_pages/home'
       end
    end
    
    def destroy
     @micropost = current_user.microposts.find_by(id: params[:id])
     return redirect_to root_url if @micropost.nil?
     @micropost.destroy
     flash[:success] = "Micropost deleted "
     redirect_to request.referrer || root_url
    end
    
    private
    def micropost_params
        params.require(:micropost).permit(:content, :picture)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user
    def create
        @user = User.find(params[:followed_id])
        current_user.follow(@user)
    end
    
    def destroy
       @user = current_user.following_relationships.find(params[:id]).followed
       current_user.unfollow(@user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "Loged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = "invalid email/password conbination"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id]=nil
    redirect_to login_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build if logged_in?
    if logged_in?
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only:[:edit,:update,:show, :followings,:followers]
  before_action :correct_user, only:[:edit,:update]
  

  def show

   @user = User.find(params[:id])
   @microposts = @user.microposts.order(created_at: :desc).page(params[:page])

  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] ="Wellcome to the Sample App"
      redirect_to @user # ここを修正
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user 
    else
      render 'edit'
    end
  end
  
  def followings
    @title = 'following users'
 #   @user =  User.find(params[:id]) #before_action で定義のため不要
    @users = @user.following_users.page(params[:page])
    render 'follow_follower_list'
  end
  
  def followers
    @title = 'follower users' #タイトル表示の文字列
  #  @user = User.find(params[:id])
    @users = @user.follower_users
    render 'follow_follower_list'
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :location,:password,:password_confirmation,:avatar)
  end
  
  def set_params
    @user = User.find(params[:id])
  end
  
  def correct_user
    redirect_to root_path if !current_user?(@user)
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
  
  def store_location
    session[:fowarding_url] = request.url if request.get?
  end
    
  def current_user?(user)
    user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user,options = {size:80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help",   '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users",'#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Seting" , edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out",logout_path,method: "delete"%>
              </li>
            </ul>
          </li>
          <% else %>
          
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>" class="clearfix">
    
    <%= link_to gravatar_for(micropost.user, size: 50) , micropost.user %>
    <div id="micropost-content">
        <span class="user"><%= link_to micropost.user.name ,micropost.user %></span>
        <span class="content"><%= auto_link(micropost.content, html: { target: '_blank' }, link: :urls) %>
        <%= image_tag micropost.picture if micropost.picture? %></span>
    </div>
    
    <div id="micropost-timestamp">
            
    <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user == micropost.user %>
         <%= link_to "delete" ,micropost , method: :delete,data: {confirm: "You sure?"} ,class:"btn btn-danger"%>
         <% end %>
      </span>
    </div>

</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count,"error") %>.
    </div>
    
    <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
    <%= render @feed_items %>
</ol>
<%= paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost ..." %>
</div>
<div class="field">
  <%= f.label :picture, "photo" %><br>
  <%= f.file_field :picture %>
</div>
<%= f.submit "Post", class: "btn btn-primary"%>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile ", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <%= render 'shared/user_info' %>
            </section>
            <section class="micropost_form">
                <%= render 'shared/micropost_form' %>
            </section>
        </aside>
        
        <div class="col-md-8">
            <h3>Microposts Feed</h3>
            <%= render 'shared/feed' %>
        </div>
    </div>
    
<% else %>
    <div class="center jumbottom">
        <h1>Welcome to the Microposts</h1>
        <%= link_to "singn up now! ",signup_path, class:"btn btn-lg btn-primary" %>
    </div>
<% end %>
    

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
<div>
    <%= hidden_field_tag :followed_id, @user.id %>
</div>
<%= f.submit "Follow", class:"btn btn-primary" %>
<% end %>

app/views/users/_follow_foloower_count.html.erb
      <div class="panel panel-default">
        <div class="panel-heading">Follows & Followers </div>
        <ul class="list-group" >
          <li class="list-group-item">
                <%= link_to "#{@user.follower_users.count} followers",followers_user_path(@user) %>  / 
                <%= link_to "#{@user.following_users.count} follows",  followings_user_path(@user) %> 
          </li>
        </ul>
        </div>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
<div id="follow_form">
 <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
    <% else %>
    <%= render 'follow' %>
    <% end %>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      
      <%= render 'form_extend', f: f if (params[:action] == 'edit' || params[:action] == 'update') %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit submit, class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_form_extend.html.erb
<%= f.label :location %>
<%= f.text_field :location, class: 'form-control' %>


<%= f.label :avatar %>
<%= f.file_field :avatar, class: 'form-control' %>

app/views/users/_location.html.erb
<div class="panel panel-default">
        <div class="panel-heading">User profile </div>
        <ul class="list-group" >
          <li class="list-group-item">
            <% if @user.location.present? %>
            <span class="label label-primary">
              <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
            </span>　<%= @user.location %>
            <% else %>
              <span class="text-danger"> no position information </span>
            <% end %>
          </li>
        </ul>
        </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id), html: {method: :delete}, remote: true) do |f| %>
<%= f.submit "Unfollow" ,class:"btn" %>
<% end %>

app/views/users/_user.html.erb
  <%#リンクなしの場合、引数の ,user は不要 %> 
<%#= link_to gravatar_for(user, size: 50), user %>
<%= link_to user do %>
<li class="list-group-item clearfix"><%= gravatar_for(user, size: 50) %> <%= user.name %>
  <% if current_user.following?(@user) %>
     <%= render 'unfollow' %>
    <% end %>
</li> 
<% end %>

app/views/users/edit.html.erb
<h1>EditProfile</h1>

<%= render 'form', submit: "Edit my account" %>

app/views/users/follow_follower_list.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user-info row">
      <h1 class='col-xs-12'>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="user-info row">  
    <div class='col-md-12' id="user-profile">
      
 
        <%= render 'follow_foloower_count' %>
<%= render 'location' %>

    </section>
  </aside>
  
  <div class="col-md-8">
    <h3><%= @title %> List </h3>
    <ul class="list-group" id="userlist"><%= render @users %></ul>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', submit: "Create my account" %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user-info row">
      <h1 class='col-xs-12'>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      
      <div class='col-xs-12' id="user-profile">
        <%= render 'follow_foloower_count' %>
        <%= render 'location' %>
      </div>
      <div class='col-xs-12' id="user-avatar">
        <%= image_tag @user.avatar, style: "width:100%;" if @user.avatar? %>
      </div>
    </section>
  </aside>
  
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
    <h3>Microposts (<%= @user.microposts.count %>)</h3>
    <ol class="microposts">
      <%= render @microposts %>
    </ol>
    <%= paginate @microposts %>
    <% end %>
  </div>
</div>